### ISSUE TITLE
Any idea why this doesn't create a popup?

### ISSUE THREAD

**Issue by scstraus** [thomasloven/lovelace-browser-commander#6]
I was able to get "debug" to give me a popup. The script is launching, the device and entity id's are both quintuple checked to be correct. But no popup.. Any idea why?
```
  launch_camera_back_popup:
    sequence:
      - event: browser_command
        event_data:
          command: more-info
          id: 080081a9-e0bfb147
          entity-id: camera.back
          large: true
```
